local deftest = require("deftest.deftest")
local audio = require("audio.audio")

function init(self)
	audio.set_logger(nil)

	deftest.add(require("test.test_audio"))
	deftest.add(require("test.test_audio_gain"))
	deftest.add(require("test.test_audio_fade"))
	deftest.add(require("test.test_audio_play_delay"))
	deftest.add(require("test.test_audio_url"))
	deftest.add(require("test.test_audio_play_host"))

	local is_report = (sys.get_config_int("test.report", 0) == 1)
	deftest.run({ coverage = { enabled = is_report } })
end
